#!/bin/sh
set -e

if [ "$1" = "remove" ] || [ "$1" = "purge" ]; then
    if [ -d /run/systemd/system ]; then
        systemctl stop rustcooling.service || true
        systemctl disable rustcooling.service || true
        systemctl daemon-reload || true
    fi
fi

exit 0
